[package]
name = "cryptoutils"
version = "0.1.0"
edition = "2024"

[lib]
name = "cryptoutils"
path = "src/lib.rs"

[[bin]]
name = "cryptoutils"
path = "src/main.rs"

[dependencies]
blake3 = "1.8.2"
rand = "0.9.1"
rayon = "1.11.0"
sha2 = "0.10.9"

[dev-dependencies]
paste = "1.0.15"
rand = "0.9.1"

[profile.release]
debug = true
